[global]

# Configurações globais do Streamlit
dataFrameSerialization = "legacy"

[server]

# Configurações do servidor
port = 8501
headless = true
runOnSave = true
allowRunOnSave = true

# Configurações de CORS
enableCORS = false
enableXsrfProtection = false

[browser]

# Configurações do navegador
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[theme]

# Tema personalizado
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]

# Configurações de log
level = "info"
messageFormat = "%(asctime)s %(message)s"